import type { ButtonConfig } from '../types';

export const buttonConfigs: ButtonConfig[] = [
  {
    id: 'round1-true',
    label: '第一輪真',
    icon: 'Check',
    group: '第一輪',
    description: '第一輪真：石化出',
    slots: { 2: '石化出' },
  },
  {
    id: 'round1-fake',
    label: '第一輪假',
    icon: 'X',
    group: '第一輪',
    description: '第一輪假：石化進',
    slots: { 2: '石化進' },
  },
  {
    id: 'round2-true',
    label: '第二輪真',
    icon: 'Check',
    group: '第二輪',
    description: '第二輪真：石化出',
    slots: { 5: '石化出' },
  },
  {
    id: 'round2-fake',
    label: '第二輪假',
    icon: 'X',
    group: '第二輪',
    description: '第二輪假：石化進',
    slots: { 5: '石化進' },
  },
  {
    id: 'fire-true',
    label: '真火',
    icon: 'Flame',
    group: '火',
    description: '真火：鋼鐵',
    slots: { 3: '鋼鐵' },
  },
  {
    id: 'fire-fake',
    label: '假火',
    icon: 'FlameKindling',
    group: '火',
    description: '假火：月環',
    slots: { 3: '月環' },
  },
  {
    id: 'water-true',
    label: '真水',
    icon: 'Droplet',
    group: '水',
    description: '真水：月環',
    slots: { 6: '月環' },
  },
  {
    id: 'water-fake',
    label: '假水',
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--ink-muted)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-droplet-off-icon lucide-droplet-off"><path d="M18.715 13.186C18.29 11.858 17.384 10.607 16 9.5c-2-1.6-3.5-4-4-6.5a10.7 10.7 0 0 1-.884 2.586"/><path d="m2 2 20 20"/><path d="M8.795 8.797A11 11 0 0 1 8 9.5C6 11.1 5 13 5 15a7 7 0 0 0 13.222 3.208"/></svg>',
    group: '水',
    description: '假水：鋼鐵',
    slots: { 6: '鋼鐵' },
  },
  {
    id: 'short-thunder',
    label: '短雷',
    icon: 'Zap',
    group: '雷水',
    description: '短雷：雷出去',
    slots: { 1: '雷出去' },
  },
  {
    id: 'long-thunder',
    label: '長雷',
    icon: 'Zap',
    group: '雷水',
    description: '長雷：雷出去',
    slots: { 4: '雷出去' },
  },
  {
    id: 'short-water',
    label: '短水',
    icon: 'ArrowBigDown',
    group: '雷水',
    description: '短水：水出去',
    slots: { 1: '水出去' },
  },
  {
    id: 'long-water',
    label: '長水',
    icon: 'ArrowBigUp',
    group: '雷水',
    description: '長水：水出去',
    slots: { 4: '水出去' },
  },
  {
    id: 'bomb-true',
    label: '有真炸彈',
    icon: 'Bomb',
    group: '炸彈',
    description: '有真炸彈：不要動',
    slots: { 1: { subText: '不要動' }, 4: { subText: '不要動' } },
  },
  {
    id: 'bomb-fake',
    label: '無真炸彈',
    icon: 'Bomb',
    group: '炸彈',
    description: '無真炸彈：必須動',
    slots: { 1: { subText: '必須動' }, 4: { subText: '必須動' } },
  },
];
